data_dir: "Y:\\Datasets\\MetaIS\\corrected\\Filtered by ICF\\"
#UWAGA: podajac te katalogi trzeba pamiętac o stworzeniu podkatalogów w models i results tak aby dla danego IS wyniki zapisywaly sie w osobnych podkatalogach
#data_dir: "Y:\\Datasets\\tmp\\"
models_dir: "Y:\\MetaIS\\models\\ICF\\" #Location where models are sotred Note that it should be algorithm specific
results_dir: "Y:\\MetaIS\\results\\ICF\\" #Location where results of the calculations are stored
n_jobs: 10
test_data_dir: "Y:\\Datasets\\Datasets\\KeelNorm\\"
datasets: [
            "abalone",
            "banana",
#          #"coil2000", #Dokładność 1NN mniejsza niż default
#          #  "kr-vs-k", #Na tym zbiorze coś się sypie
            "letter",
            "magic",
            "marketing",
            "nursery",
            "optdigits",
            "page-blocks",
           "penbased",
            "phoneme",
            "ring",
            "satimage",
     #       "shuttle",
            "spambase",
     #       "splice",
            "texture",
            #"thyroid", #Dokładność 1NN mniejsza niż default
            "twonorm"
]
result_postfix: "v3"
treshholds: [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]
